---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/sentinel --version
    register: sentinel_test_output
  - name: sentinel --version
    debug:
      msg: '{{ sentinel_test_output.stdout }}'
