---
- name: Testing andrewrothstein.sentinel
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'sentinel --version'
      ansible.builtin.command: sentinel --version
      changed_when: false
      register: sentinel_test_output
    - name: Output of 'sentinel --version'
      ansible.builtin.debug:
        msg: '{{ sentinel_test_output.stdout }}'
