---
- name: Installing sentinel binaries
  ansible.builtin.include_role:
    name: andrewrothstein.hashi
  vars:
    hashi_apps:
      - name: '{{ sentinel_app.name | default("sentinel") }}'
        ver: '{{ sentinel_app.ver | default(sentinel_ver) }}'
        meta: '{{ sentinel_app.meta | default("") }}'
